### ISSUE TITLE
On macos the credentials are not written to disk

### ISSUE THREAD

**Issue by cleygraf** [rubrikinc/rubrik-module-for-powershell-backup-validation#2]
**Expected Behavior**

New-BuildConfiguration writes credentials to disk

**Current Behavior**

The credentials are not written to disk. The part for macos is empty in New-SecureCredential.

**Failure Information (for bugs)**

I will try to fix and then issue a pull request.

Please help provide information about the failure if this is a bug.

* Use verbose outputs to capture any debug information.
* Paste into a code block.

**Steps to Reproduce**

Please provide detailed steps for reproducing the issue.

* Use numbered list.

**Context**

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Version of project.
* Version of dependencies.
* Version of operating system.

**Failure Logs**

Please include any relevant log snippets or files here.

* Use verbose outputs to capture any debug information.
* Paste into a code block.

    switch (Get-PowerShellVersion) {
        'Windows' {
            if (-not (Test-FolderStructure -Credential)) {
                $null = New-Item -Path './credential' -ItemType Directory
            }
            
            'RubrikCred', 'VMwareCred', 'GuestCred' | ForEach-Object {
                $Credential = (Get-Item variable:$_).Value
                $Credential | Export-Clixml -Path $(Join-Path $Path "$_.xml")
            }
        }
        'macOS' {

        }
        default {Write-Error 'Current OS platform not supported '}

**Comment by jaapbrasser** [comment]
Thanks for reporting this @cleygraf, I have the initial code for MacOS support written up. I will integrate and check back with you early next week.

**Comment by cleygraf** [comment]
Hi Japp

Let's have a quick sync on Slack later today. I've lined up a multitude of
changes to this and to the "use case" repository.

Cheers,

Christoph

PS.: You can reach out to me via christoph.leygraf@rubrik.com
--
Christoph Leygraf
Karl-Müller-Str. 14/5
71409 Schwaikheim

+49 151 22683645

christoph@leygraf.de



Am Fr., 12. Juli 2019 um 15:21 Uhr schrieb Jaap Brasser <
notifications@github.com>:

**Comment by jaapbrasser** [comment]
Fixed in #3
