### ISSUE TITLE
Configuration json created has not the proper structure

### ISSUE THREAD

**Issue by cleygraf** [rubrikinc/rubrik-module-for-powershell-backup-validation#4]
The configuration json created by `New-BuildConfiguration` and `New-ConfigJson` has not the expected format and in consequence, no testing is done.

The scripts in _use-case-powershell-backup_-validation expect a top-level element "virtualMachines" and all the virtual machines to test below. `New-ConfigJson` omits this top-level element. 

**Expected Behavior**

The created configuration file is in the expected format and test will be done.
 
**Current Behavior**

What is the current behavior?

Poper configuration json file is written.

Please help provide information about the failure if this is a bug.

I will file a pull request with a fix.

**Steps to Reproduce**

Run `New-BuildConfiguration` or `New-ConfigJson` and issue an Invoke-Build afterward: No errors, but no tests too! 

* Use numbered list.

**Context**

Change 

```
    $CurrentConfig = [pscustomobject]$MyInvocation.BoundParameters
    $CurrentConfig.TestIp = $CurrentConfig.TestIp.ToString()
    $CurrentConfig.TestGateway = $CurrentConfig.TestGateway.ToString()

```

to

```
    $CurrentConfig = [pscustomobject]@{"virtualMachines" = ,@{
        name = $Name
        mountName = $MountName
        testIp = $TestIp.ToString()
        testNetwork = $TestNetwork
        testSubnet = $TestSubnet
        testGateway = $TestGateway.ToString()
        tasks = $Tasks
    }

```

* Version of project.
* Version of dependencies.
* Version of operating system.

**Failure Logs**

Please include any relevant log snippets or files here.

**Comment by jaapbrasser** [comment]
Fixed in #3
